# Generated by Django 5.0.9 on 2024-12-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city_of_origin",
            field=models.CharField(
                default="Los Angeles", max_length=180, verbose_name="City"
            ),
        ),
    ]
